# Generated by Django 4.1.4 on 2024-02-03 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_web_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("date_naissance", models.DateField()),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Men"), ("F", "Women")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("marque", models.CharField(max_length=255)),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        validators=[my_web_app.models.validate]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(default=my_web_app.models.payment, max_length=50),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_web_app.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_web_app.product",
                    ),
                ),
            ],
        ),
    ]
