# Generated by Django 4.1.4 on 2024-02-05 12:28

from django.db import migrations, models
import my_web_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_web_app", "0002_alter_command_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReachoutModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=155, validators=[my_web_app.models.check_name]
                    ),
                ),
                ("prenom", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("verify_email", models.EmailField(max_length=254)),
                ("commentaire", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="command",
            name="id",
            field=models.TextField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
