# Generated by Django 4.1.4 on 2024-02-05 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_web_app", "0003_reachoutmodel_alter_command_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="id",
            field=models.TextField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="reachoutmodel",
            name="commentaire",
            field=models.TextField(max_length=1500),
        ),
    ]
