# Generated by Django 4.1.4 on 2024-02-06 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_web_app", "0006_alter_command_id_userpofilemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reachoutmodel",
            name="verify_email",
        ),
        migrations.AlterField(
            model_name="command",
            name="id",
            field=models.TextField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
