# Generated by Django 4.1.4 on 2024-02-06 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_web_app", "0007_remove_reachoutmodel_verify_email_alter_command_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("principal", models.CharField(max_length=250)),
                ("location", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="command",
            name="id",
            field=models.TextField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="my_web_app.schoolmodel",
                    ),
                ),
            ],
        ),
    ]
